In [2]:
import torch

print("=" * 50)
print("🧩 张量创建方式")
print("=" * 50)

# 从列表创建
t1 = torch.tensor([[1, 2], [3, 4]])
print(f"从列表:      {t1.shape}, dtype={t1.dtype}")

# 全 0 / 全 1 / 单位矩阵
t2 = torch.zeros(2, 3)
t3 = torch.ones(2, 3)
t4 = torch.eye(3)
print(f"全零:         {t2}")
print(f"全一:         {t3}")
print(f"单位矩阵:\n{t4}")

# 随机张量
t5 = torch.rand(2, 3)       # 均匀分布 [0,1)
t6 = torch.randn(2, 3)      # 标准正态分布
print(f"均匀随机:     {t5}")
print(f"正态随机:     {t6}")

# 指定 dtype 和设备
t7 = torch.tensor([1.5, 2.5], dtype=torch.float32)
print(f"指定 float32: {t7.dtype}")

print()

print("=" * 50)
print("🔧 张量变形 & 索引")
print("=" * 50)

t = torch.arange(12).reshape(3, 4)
print(f"arange(12).reshape(3,4):\n{t}")

print(f"t[1,2] = {t[1,2].item()}")           # 取值 → Python 标量
print(f"t[:, 1:3]:\n{t[:, 1:3]}")            # 切片

t_flat = t.view(-1)                           # 展平
print(f"view(-1) 展平: {t_flat}")

t_t = t.t()                                    # 转置
print(f"转置 shape: {t_t.shape}")

print()

print("=" * 50)
print("🧮 数学运算")
print("=" * 50)

a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"a + b:\n{a + b}")
print(f"a - b:\n{a - b}")
print(f"a * b (逐元素乘):\n{a * b}")
print(f"a @ b (矩阵乘):\n{a @ b}")
print(f"a.mean() = {a.mean().item():.2f}")
print(f"a.sum()  = {a.sum().item()}")
print(f"a.pow(2):\n{a.pow(2)}")
print(f"a.sqrt():\n{a.sqrt()}")
print(f"a.exp():\n{a.exp()}")
print()

print("=" * 50)
print("⚡ 自动求导 (backward)")
print("=" * 50)

# 单变量
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 2 * x            # y = x³ + 2x
y.backward()
print(f"y = x³ + 2x, x=2.0")
print(f"dy/dx = {x.grad.item()}")   # 3x² + 2 = 14
print()

# 多变量（矩阵）
x2 = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
z = x2.pow(2).sum()           # z = sum(x²)
z.backward()
print(f"z = sum(x²), x = [[1,2],[3,4]]")
print(f"dz/dx = \n{x2.grad}")        # 2x
print()

print("=" * 50)
print("🎮 GPU 加速")
print("=" * 50)

if torch.cuda.is_available():
    device = torch.device("cuda")
    t_cpu = torch.rand(1000, 1000)
    t_gpu = t_cpu.to(device)
    
    print(f"CPU tensor:  {t_cpu.device}")
    print(f"GPU tensor:  {t_gpu.device}")
    
    # 速度对比
    import time
    
    start = time.time()
    _ = t_cpu @ t_cpu
    cpu_time = time.time() - start
    
    start = time.time()
    _ = t_gpu @ t_gpu
    torch.cuda.synchronize()
    gpu_time = time.time() - start
    
    print(f"\n矩阵乘法 1000×1000 对比:")
    print(f"  CPU: {cpu_time:.4f}s")
    print(f"  GPU: {gpu_time:.4f}s")
    print(f"  加速比: {cpu_time/gpu_time:.1f}x")
else:
    print("本机无 GPU，用 CPU 替代演示")
print()

print("=" * 50)
print("📦 与 NumPy 互转")
print("=" * 50)

import numpy as np
arr_np = np.array([[1, 2], [3, 4]], dtype=np.float32)
t_from_np = torch.from_numpy(arr_np)
arr_from_t = t_from_np.numpy()
print(f"NumPy → Torch: {t_from_np.dtype} on {t_from_np.device}")
print(f"Torch → NumPy: {arr_from_t.dtype}")
print(f"共享内存: {np.shares_memory(arr_np, arr_from_t)}")  # True！改一个另一个也会变

🧩 张量创建方式
从列表:      torch.Size([2, 2]), dtype=torch.int64
全零:         tensor([[0., 0., 0.],
        [0., 0., 0.]])
全一:         tensor([[1., 1., 1.],
        [1., 1., 1.]])
单位矩阵:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
均匀随机:     tensor([[0.2813, 0.9679, 0.4459],
        [0.7066, 0.5859, 0.2224]])
正态随机:     tensor([[ 0.2922, -0.2829,  0.0497],
        [-0.0206,  0.0245,  0.7705]])
指定 float32: torch.float32

🔧 张量变形 & 索引
arange(12).reshape(3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
t[1,2] = 6
t[:, 1:3]:
tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])
view(-1) 展平: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
转置 shape: torch.Size([4, 3])

🧮 数学运算
a + b:
tensor([[ 6.,  8.],
        [10., 12.]])
a - b:
tensor([[-4., -4.],
        [-4., -4.]])
a * b (逐元素乘):
tensor([[ 5., 12.],
        [21., 32.]])
a @ b (矩阵乘):
tensor([[19., 22.],
        [43., 50.]])
a.mean() = 2.50
a.sum()  = 10.0
a.pow(2):
tensor([[ 1.,  4.]